[gcp_service_account]
type = "service_account"
project_id = "opj-bot"
private_key_id = "721f2ea981984e86046be319d02d41ca78b120f6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGuBXLKvjgp/fj
BYuSVc/iSQmRAaoohaiHuKphGMX2ILVuhVtYY6rArv7Um88R1sgYVpv4mp190uwc
hRC0FyX26XzMKAoNLS8qnI/b9651qP/wrmqlEjm9g6vzUhCR4zYS4559bHAW2ifx
d3p4hfArBAaWvf6KgQ6DxrJLm73M+QbUM5dWv8/ra6l7wry2X8rRlTqoE9c5hXPw
H/vlqy8Sb8YYcZfCC4jqIdtZHRYVgghEobCaKOyDVSt9Mdr1KwGGNHBf1TXpuF4q
20hyVrkduY096apOiO2cFsz/PXfXGCga1kl+6YwEXIllJJIYl/TUoL2U14b8hue9
gkTQ71plAgMBAAECggEAHWCMdD8TkN60Aj9JHWaLN3g1rlaxKZFs0zelFHqdlV/L
gp27XctKLHcSXCr2hzwZ06NGJo/w9W9vkV3IlN8RMTneRa4rojwKS4HesJWimGlW
AOZABMw3dgFXs75vjampzkwRG5iiz3YLzqIrnFKsqSdMtA89aItgsnF23T+WZQ0u
iETw8uZ2FgyFkTbX/4/nDVFWd/FSJd2/o1VEgvvPGKz+k5KwcWNRw9yokveAX3xo
qiRBt8UjMrUuGP1dgl5e/agz7wY7oYZNGJg/IvlHVcW7BCZnW3CVBgMB5QcBnVPi
4FwbsSR3YLgzoNvYPfWACkueN8a4ikUTtwIQu96mIQKBgQD4rZdVr47C+nHzemJj
9fKfTfFWpDXBeln9Z0VnnIAPm+4ZWkqmOl5azqGZUloQV+beyBk9V7dbMj4pr+Ws
3iErhYxyBNYtMmCkyOZphNIetT/vED3p1tRMTdGskJYzxtrz1lJ8uql3lujTOLFh
Y/6y6qkAtE7uj2LDEMxqrE3T0QKBgQDMke2sZK/lGFRrFvdje19SPqBDXlviAWOE
/GDF4BNM5dZ5FXkvVN8F8IagqEi6OUxdTP/98LvsS6ZiQUGY/djgsKD50WFjzY2V
nm8mfkpkxGPrAyFcr3kt3m46E7nblCYcQgr3ZmgJDMQUze8XTZcWwGoQVaRAwt0th
xpj6f/cmVQKBgQCbaAB3L+tLti+YNRdf2Mfy/kagGqbtboTmc69P/OGa35uAhIi6
MSfeH9ulcW2PYR+Kggoj57lSaKeobaBe08Ju7FrEtnkSbbUvxc0YjESzpBl8UO4g
QH0T4l3yNbloShFy6LFL+WsGrWx686cGcfMt5LARHJ1nQHw74zecQmmwwQKBgQDC
hajJGt0fLWlog2guUqwrWp2uMdWRLNzjIdErl40CvDKa5M5dMYj47uQ1dI/jdISm
24c4g2dOpAjMuVyVDBzkW1BW/MBs1JLjRkYM1KuSwjv+gQJTFogQbfyxbsfjtpGW
I5w/hHDOT5iwget0vvuiHzSl30ej60dk7CGfYXs0GQKBgFKAQ2DLc9wZO4EHzi4e
7xvy8PCX+MIGkdK69XgcJZ6q7wx5E+dE0yW+mmUKKBMOQrzDrBE/xJ9boxZ7Ev1E
niaxmhgArSn9CwmK60fYq1f0F+H7HssibrAXDUYqNgBIka+SnL+e6VvBZ6M97DqYI
7jd7JbYmjE1DimBr3Br276UB
-----END PRIVATE KEY-----"""
client_email = "opj-connector@opj-bot.iam.gserviceaccount.com"
client_id = "112242616526089361581"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/opj-connector%40opj-bot.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
